import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Arizonia&family=Khand:wght@300;400;500;600;700&display=swap');
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        <Navbar />
        <main
          style={{
            background: "linear-gradient(to bottom, #1a1a1a, #8c8c8c)", // Changed from #4d4d4d to #1a1a1a
          }}
          className="pt-[150px] min-h-[119vh]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
